### ISSUE TITLE
error while executing clorkworksms handler

### ISSUE THREAD

**Issue by albdv** [sensu-plugins/sensu-plugins-clockworksms#1]
While trying to execute handler got an error.
Here is a stacktrace

root@monitoring:/opt/sensu/embedded/bin# ruby ./handler-clockworksms.rb 
/opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:52:in `<module:Net>': uninitialized constant Timeout::Error (NameError)
    from /opt/sensu/embedded/lib/ruby/2.0.0/net/protocol.rb:24:in`<top (required)>'
    from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:22:in `<top (required)>'
    from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:1:in`<top (required)>'
    from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-clockworksms-0.0.3/bin/handler-clockworksms.rb:14:in `<top (required)>'
    from ./handler-clockworksms.rb:23:in`load'
    from ./handler-clockworksms.rb:23:in `<main>'

**Comment by eheydrick** [comment]
The problem was a conflict between the built-in timeout and the timeout gem. In reality the handler didn't actually use timeout at all so I've removed that dependency and I'm not getting that error anymore. I released the fix in version [0.0.4](https://rubygems.org/gems/sensu-plugins-clockworksms/versions/0.0.4). Can you try that.
